import { db } from "../db";
import type { Placement, Student } from "../types";

export const SAMPLE_STUDENTS: Omit<Student, "id">[] = [
  { name: "Oliver Bennett", postcode: "E8 1EA", year: 1, isDriver: true },
  { name: "Amelia Foster", postcode: "E9 6HA", year: 2, isDriver: false },
  { name: "Jack Reynolds", postcode: "E17 5NT", year: 3, isDriver: true },
  { name: "Isla Whitfield", postcode: "E3 4PX", year: 1, isDriver: false },
  { name: "Harry Sullivan", postcode: "N1 5AH", year: 2, isDriver: true },
  { name: "Sophia Marsh", postcode: "N16 8HP", year: 3, isDriver: false },
  { name: "Charlie Doyle", postcode: "NW1 8AH", year: 1, isDriver: false },
  { name: "Grace Whitmore", postcode: "NW5 2LH", year: 2, isDriver: true },
  { name: "Thomas Coleman", postcode: "NW10 4UA", year: 3, isDriver: false },
  { name: "Ruby Sinclair", postcode: "SE8 3FA", year: 1, isDriver: true },
  { name: "George Fletcher", postcode: "SE10 8EW", year: 2, isDriver: false },
  { name: "Freya Hutton", postcode: "SE13 5EW", year: 3, isDriver: false },
  { name: "Jacob Pearce", postcode: "SE15 4ST", year: 1, isDriver: true },
  { name: "Chloe Sanderson", postcode: "SE22 8EP", year: 2, isDriver: false },
  { name: "Oscar Mahoney", postcode: "SW4 7AA", year: 3, isDriver: true },
  { name: "Lily Radcliffe", postcode: "SW9 8QF", year: 1, isDriver: false },
  { name: "Leo Winters", postcode: "SW11 5TN", year: 2, isDriver: true },
  { name: "Ella Sherwood", postcode: "SW12 8LF", year: 3, isDriver: false },
  { name: "Daniel Osei", postcode: "SW18 1NN", year: 1, isDriver: false },
  { name: "Poppy Ahmed", postcode: "W3 7SN", year: 2, isDriver: true },
  { name: "Ethan Walsh", postcode: "W5 5RG", year: 3, isDriver: false },
  { name: "Mia Chowdhury", postcode: "W10 5SP", year: 1, isDriver: true },
  { name: "Alfie Grant", postcode: "W12 7SB", year: 2, isDriver: false },
  { name: "Evie Nguyen", postcode: "TW9 1DN", year: 3, isDriver: false },
  { name: "Joshua Patel", postcode: "CR0 1LA", year: 1, isDriver: true },
  { name: "Zara Hussain", postcode: "BR1 1DN", year: 2, isDriver: false },
  { name: "Finn Carter", postcode: "IG1 1RS", year: 3, isDriver: true },
  { name: "Layla Khan", postcode: "DA6 8HX", year: 1, isDriver: false },
  { name: "Arthur Bishop", postcode: "RM1 1JU", year: 2, isDriver: false },
  { name: "Nina Okafor", postcode: "SE9 6TE", year: 3, isDriver: true },
];

export const SAMPLE_PLACEMENTS: Omit<Placement, "id">[] = [
  {
    name: "St Thomas' Hospital",
    postcode: "SE1 7EH",
    category: "adult",
    yearsOffered: [1, 2, 3],
    requiresDriver: false,
    capacity: 3,
  },
  {
    name: "Royal Free Hospital",
    postcode: "NW3 2QG",
    category: "adult",
    yearsOffered: [1, 2, 3],
    requiresDriver: false,
    capacity: 3,
  },
  {
    name: "Great Ormond Street Hospital",
    postcode: "WC1N 3JH",
    category: "paediatric",
    yearsOffered: [2, 3],
    requiresDriver: false,
    capacity: 2,
  },
  {
    name: "King's College Hospital",
    postcode: "SE5 9RS",
    category: "adult",
    yearsOffered: [1, 2, 3],
    requiresDriver: false,
    capacity: 3,
  },
  {
    name: "Royal London Hospital",
    postcode: "E1 1FR",
    category: "adult",
    yearsOffered: [1, 2, 3],
    requiresDriver: false,
    capacity: 3,
  },
  {
    name: "Homerton University Hospital",
    postcode: "E9 6SR",
    category: "paediatric",
    yearsOffered: [1, 2, 3],
    requiresDriver: false,
    capacity: 2,
  },
  {
    name: "Whittington Hospital",
    postcode: "N19 5NF",
    category: "adult",
    yearsOffered: [2, 3],
    requiresDriver: false,
    capacity: 2,
  },
  {
    name: "Chelsea and Westminster Hospital",
    postcode: "SW10 9NH",
    category: "paediatric",
    yearsOffered: [1, 2, 3],
    requiresDriver: false,
    capacity: 2,
  },
  {
    name: "University College Hospital",
    postcode: "NW1 2BU",
    category: "adult",
    yearsOffered: [1, 2, 3],
    requiresDriver: false,
    capacity: 3,
  },
  {
    name: "Croydon Community Paediatric Team",
    postcode: "CR7 7YE",
    category: "paediatric",
    yearsOffered: [2, 3],
    requiresDriver: true,
    capacity: 1,
  },
  {
    name: "Enfield Adult Community Rehab",
    postcode: "EN2 0JB",
    category: "adult",
    yearsOffered: [2, 3],
    requiresDriver: true,
    capacity: 1,
  },
  {
    name: "Bromley Community Health Team",
    postcode: "BR6 8ND",
    category: "adult",
    yearsOffered: [2, 3],
    requiresDriver: true,
    capacity: 1,
  },
];

export async function loadSampleData(): Promise<void> {
  await db.students.bulkAdd(SAMPLE_STUDENTS.map((s) => ({ ...s, id: crypto.randomUUID() })));
  await db.placements.bulkAdd(SAMPLE_PLACEMENTS.map((p) => ({ ...p, id: crypto.randomUUID() })));
}
